python scripts/train_lightning_model.py \
    dataset=longitudinal_dummy_smart \
    dataset.root_path=data/dummy_data/longitudinal_dummy_smart \
    model=llm \
    model.llm_name=meta-llama/Llama-3.2-1B \
    "model.llm_config_overrides.num_key_value_heads=4" \
    "model.llm_config_overrides.num_hidden_layers=3" \
    "model.llm_config_overrides.hidden_size=512" \
    "model.llm_config_overrides.intermediate_size=1024" \
    "model.llm_config_overrides.num_attention_heads=4" \
    "model.llm_config_overrides.head_dim=16" \
    training=lightning \
    training/task=binary_classification \
    training.batch_size=4 \
    training.accumulation_steps=8 \
    "training.devices=[0]" \
    training.num_workers=0 \
    training.lr=2e-4 \
    training.epochs=10
