defaults:
  - base_llm

name: llm
llm_name: meta-llama/Llama-3.2-1B
llm_config_overrides:
  num_key_value_heads: 4
  num_hidden_layers: 3
  hidden_size: 512
  intermediate_size: 1024
  num_attention_heads: 4
  head_dim: 16
max_tokens: null
freeze_backbone: false
gradient_checkpointing: false
chunk_size: null