defaults:
  - base_weighted_lstm

name: weighted_lstm
vocab_path: data/mimic_los/vocabs/preprocessed/
lang: en
time_embedding_dim: 64
lstm_hidden_size: 512
lstm_dropout: 0.0
alpha_r: 0.5
data_types: all