dataset_params:
  dataset_name: smart
  params:
    root_path: data/smart
    use_full_feature_set: true
model_params:
  batch_norm: true
  dropout: 0.2
  model_name: mtlr
  num_nodes:
  - 256
  - 256
  - 256
  - 256
  output_bias: true
train_params:
  batch_size: 256
  device: cpu
  epochs: 500
  patience: 10
